name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout/@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t zrwhits/iws-client --build-arg REACT_APP_NODE_ENV='production' --build-arg REACT_APP_BACKEND_URL='${{ secrets.REACT_APP_BACKEND_URL }}' .
      - name: Publish Image to docker hub
        run: docker push zrwhits/iws-client:latest

  deploy: 
    needs: build
    runs-on: self-hosted 
    steps: 
      - name: Pull Image from docker hub
        run: docker pull zrwhits/iws-client:latest
      - name: Delete old container
        run: docker rm -f iws-client-container
      - name: Run Docker Container 
        run: docker run -d -p 3000:80 --name iws-client-container zrwhits/iws-client
